name: Address, memory and thread santizer build workflows

on:
  workflow_call:

jobs:
  sanitizer-unix:
    name: Ubuntu/MacOSX
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-12, macos-11]
        sanitizer: [ address, memory, thread, undef ]
    env:
      builder:
        ${{ (startsWith( matrix.os, 'ubuntu' ) && 'ninja') || 
            (startsWith( matrix.os, 'macos') && 'xcode') }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Linux dependencies
      if: ${{ !contains( matrix.os, 'macos') }}
      run: |
        sh -ex .travis/deps.sh linux
        sudo apt install -ym ninja-build
    - name: Install MacOSX dependencies
      if: ${{ contains( matrix.os, 'macos') }}
      run: |
        sh -ex .travis/deps.sh osx
    - name: cmake-builder.sh
      run: |
        cmake/cmake-builder.sh --config Debug --flavor ${{ env.builder }} --sanitizer ${{ matrix.sanitizer }} --notest --parallel --verbose
    - name: SIMH simulator suite test
      run: |
        cmake/cmake-builder.sh --config Debug --flavor ${{ env.builder }} --sanitizer ${{ matrix.sanitizer }} --testonly

  cmake-vs2022:
    name: VS 2022 Win10 native VCPKG
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [windows-latest]
        sanitizer: [ address, memory, thread, undef ]
    steps:
    - uses: actions/checkout@v3
    - name: vs2022 build
      shell: pwsh
      run: |
          $ErrorActionPreference="Stop"
          $WarningPreference="Continue"
          # Fix PATH so that "C:\Strawberry" (Strawberry Perl) doesn't mess with the build
          # CMake WILL find incompatible libraries within Strawberry.
          $fixPATH = (${env:PATH}.Split(';') | `
              Where-Object { $_ -notlike "*\Strawberry\*" -and $_ -notlike "*/Strawberry/*" }) -join ';'
          $env:PATH = $fixPATH
          # Make this a vcpkg build:
          $env:VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT
          Push-Location $env:VCPKG_ROOT
          git pull
          Pop-Location
          ./cmake/cmake-builder.ps1 -flavor vs2022 -config Debug -clean -sanitizer ${{ matrix.sanitizer }} -notest --parallel -verbose
    - name: SIMH simulator suite test
      shell: pwsh
      run: |
          ./cmake/cmake-builder.ps1 -flavor vs2022 -config Debug -sanitizer ${{ matrix.sanitizer }} -testOnly
